apiVersion: v1
data:
  default.conf: |-
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      #access_log  /var/log/nginx/host.access.log  main;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      #error_page  404              /404.html;

      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }

      location /stats {
          proxy_pass http://demo-backend-http.demo-backend:5000;
      }
    }
kind: ConfigMap
metadata:
  name: {{ include "demo-frontend.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels: {{- include "demo-frontend.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl ( .Values.commonLabels | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.configmap.labels }}
    {{- tpl ( .Values.configmap.labels | toYaml ) . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- tpl ( .Values.commonAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.configmap.annotations }}
    {{- tpl ( .Values.configmap.annotations | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.configmap.commonAnnotations }}
    {{- tpl ( .Values.configmap.commonAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}