apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-frontend.service.http.name" . }}
  namespace: {{ .Values.namespace }}
  labels: {{- include "demo-frontend.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- tpl ( .Values.commonLabels | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.service.labels }}
    {{- tpl ( .Values.service.labels | toYaml ) . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- tpl ( .Values.commonAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.service.annotations }}
    {{- tpl ( .Values.service.annotations | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.service.commonAnnotations }}
    {{- tpl ( .Values.service.commonAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}
    {{- if .Values.service.httpAnnotations }}
    {{- tpl ( .Values.service.httpAnnotations | toYaml ) . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ include "demo-frontend.service.http.port" . }}
      targetPort: http
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.http)) }}
      nodePort: {{ .Values.service.nodePorts.http }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.service.extraPorts }}
    {{- tpl ( .Values.service.extraPorts | toYaml ) . | nindent 4 }}
    {{- end }}
  selector: {{- include "demo-frontend.selectorLabels" . | nindent 4 }}