apiVersion: v1
data:
  config.json: |-
  {{- if .Values.app.socks.enabled }}
    {
      "log": {
          "loglevel": "debug"
      },
      "routing": {
          "domainStrategy": "AsIs",
          "rules": [
              {
                  "type": "field",
                  "ip": [
                      "geoip:private"
                  ],
                  "outboundTag": "block"
              }
          ]
      },
      "inbounds": [
          {
              "listen": "0.0.0.0",
              "port": {{ .Values.service.port }},
              "protocol": "socks",
              "settings": {
                  "auth": "noauth",
                  "udp": false
              }
          }
      ],
      "outbounds": [
          {
              "protocol": "freedom",
              "tag": "direct"
          },
          {
              "protocol": "blackhole",
              "tag": "block"
          }
      ]
    }  
  {{- end}}
kind: ConfigMap
metadata:
  labels: 
  {{- include "proxy.labels" . | nindent  4 }}
  name: {{ include "proxy.fullname" . }}
  namespace: {{ .Values.namespace }}