apiVersion: {{ .Values.k8sApiVersion | default "extensions/v1beta1" }}
kind: Deployment
metadata:
  name: {{ include "proxy.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels: 
    {{- include "proxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "proxy.selectorLabels" .| nindent 6 }}
  replicas: {{ .Values.deploy.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels: {{- include "proxy.labels" . | nindent 8  }}
    spec:
{{- with .Values.deploy.hostAliases}}      
      hostAliases:
{{ toYaml . | indent 8}}
{{- end }}
      containers:
      - image: {{ include "proxy.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        name: v2fly
        ports:
        - containerPort: {{ .Values.service.port }}
          name: proxy
          protocol: TCP
        {{- if .Values.app.http.enabled }}  
        - containerPort: {{ .Values.service.httpPort }}
          name: proxy-http
          protocol: TCP
        {{- end}}
        volumeMounts:
        - mountPath: /etc/v2ray
          name: config-volume
        resources:
          requests:
            cpu: "1"
            ephemeral-storage: 40Gi
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ include "proxy.fullname" . }}
          name: config-volume