namespace: proxy
fullnameOverride: proxy
image:
  registry: "docker.io"
  repository: "v2fly/v2fly-core"
  tag: "v4.45.0"
  pullPolicy: IfNotPresent
k8sApiVersion: "extensions/v1beta1"
service:
  type: ClusterIP
  port: 9000
  ambassador:
    enabled: true
# add nodePort to ambassador
# spec:
#   ports:
#   - name: tcp9000
#     nodePort: 30900
#     port: 9000
#     protocol: TCP
#     targetPort: 9000      
deploy:
  replicas: 1
  hostAliases: []
dnsConfig: {}
app:
  socks:
    enabled: true