nameOverride: ""
namespace: demo-frontend
image:
  registry: "quay.io"
  repository: "yushiwho/sys-stats"
  tag: "e1f9d77"
  pullPolicy: IfNotPresent 
fullnameOverride: ""
commonLabels: {}
commonAnnotations: {}
selectorLabels: {}
configmap:
  name: conf
service:
  type: ClusterIP
  ports:
    http: 8080
  nodePorts:
    http: ""
    grpc: ""

serviceAccount:
  create: true
  labels: {}
  annotations: {}
  imagePullSecrets: []

deployment:
  replicas: 1
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  extraVolumeMounts: {}
  lifecycleHooks: {}
  backendHost: "localhost:5000"
  resources:
    limits:
      memory: 256Mi
      cpu: 100m
    requests:
      memory: 256Mi
      cpu: 100m
  podSecurityContext:
    enabled: false
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534      
  # affinity, tolerations, hostNetwork, etc.  
  extraPodSpec: {}
  extraVolumes: []

ingress:
  create: true
  labels: {}
  host: ""
  commonAnnotations:
    alb.ingress.kubernetes.io/group.name: demo
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8080}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  grpcAnnotations: {}
  ingressClassName: "alb"
  httpIngressClassName: ""
  grpcIngressClassName: ""
  tls: []
  httpTls: []
  grpcTls: []
  httpExtraPaths:
    prepend: []
    append: []
  grpcExtraPaths:
    prepend: []
    append: []